@url_dev=http://localhost:3000/v1/api/product

### Create product 
POST http://localhost:3000/v1/api/product
Content-Type: application/json
x-api-key: b462c35f781d44a137302b1a2fb9a7b4d13a24e9b2ca4007effe625088ffa133caf03623250b09082b33c98c1b60b8b07f8e9aa5af21f23236b2a9e2c8ecf829
x-client-id: 668ce9080dfc015d9af8cd86
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiI2NjhjZTkwODBkZmMwMTVkOWFmOGNkODYiLCJlbWFpbCI6Ik5oTGluaDNAZ21haWwuY29tIiwiaWF0IjoxNzIwNTQyMDE0LCJleHAiOjE3MjA3MTQ4MTR9.ZKw-eYDsCDwhsR9gL4ntE7dlGRLjyUVtfke63U36-HM

{
    "product_name": "New Jeans", 
    "product_description": "High-quality denim jeans", 
    "product_price": 50, 
    "product_shop": "668ce9080dfc015d9af8cd86", 
    "product_type": "Clothing", 
    "product_thumb": "product_thumb", 
    "product_quantity": 5, 
    "product_attributes": {
        "brand": "Levi", 
        "size": "L", 
        "material": "Denim"
    }
}
